# Generated by Django 2.1.5 on 2019-01-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('FINAL', 'FINAL')], default='DRAFT', max_length=12)),
            ],
        ),
    ]
